//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_ASP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_de_Pedido
    {
        public int IdLineaDePedido { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<int> IdArticlo { get; set; }
        public Nullable<int> CantidadPedido { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> SubTotal { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
