//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_ASP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListArticulos
    {
        public int ID { get; set; }
        public string Codigo_Articulo { get; set; }
        public string Descripcion { get; set; }
        public string Codigo_Categoria { get; set; }
        public string Nombre_Categoria { get; set; }
        public Nullable<double> Precio { get; set; }
    }
}
