//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_ASP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string TerminoPago { get; set; }
        public Nullable<double> TotalPedido { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
